### ISSUE TITLE
The Implementation seems wrong.

### ISSUE THREAD

**Issue by Ti-tanium** [divyanshu013/aks-parallel#7]
I tried a few tests and it returned false results.

I tested `2, 3, 7, 11`, and it all returned false, which is wrong.

I know this repo is probably not maintained anymore, just want to give a heads up to whoever wants to try this repo.

**Comment by prateekprshr-nith** [comment]
The algorithm fails for numbers <= 53. Please check  https://github.com/divyanshu013/aks-parallel/blob/master/aksSerial/aksSerial/test.cpp.
